version: "3"
services:
  api:
    container_name: backend_ut
    image: segiraldovi/my_back
    build: ./
    ports:
      - 8081:8081
    environment:
      - DB_URL=postgres
      - POSTGRES_PORT=5432
